### ISSUE TITLE
Reflection error when calling AddAspNetCore

### ISSUE THREAD

**Issue by stevencovhlth** [simpleinjector/SimpleInjector.Integration.AspNetCore#2]
> System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'Vortext.Common.Domain.Model.Entity' from assembly 'Vortext.Common.Domain, Version=1.7.6.0, Culture=neutral, PublicKeyToken=null'.

I get 4 of these on the call to `options.AddAspNetCore()`

``` c#
 private void IntegrateSimpleInjector(IServiceCollection services)
{
    _container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

    services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

    services.AddSingleton<IControllerActivator>(new SimpleInjectorControllerActivator(_container));
    services.AddSingleton<IViewComponentActivator>(new SimpleInjectorViewComponentActivator(_container));

    services.AddSimpleInjector(_container, options =>
    {
        // AddAspNetCore() wraps web requests in a Simple Injector scope.
        options.AddAspNetCore()
            // Ensure activation of a specific framework type to be created by
            // Simple Injector instead of the built-in configuration system.
            .AddControllerActivation();
    });

    Bootstrapper.Bootstrap(_container, Configuration);

}
```
No other information about why or anything.  I tried moving the SimpleInjector registrations before this call but still no luck.  Clearly this is a problem with my library not yours but is there some way to better troubleshoot the actual problem?  The `Entity` object in question is actually an abstract class so I don't understand why it would be constructed anyway.

I've called container.Verify() before` AddSimpleInjector()` in order to troubleshoot things and the errors I get are things that I am already register in the services collection, e.g. `IHttpContextAccessor` (see line 5 in code above)

**Comment by stevencovhlth** [comment]
*not* calling `options.AddAspNetCore()` gives me this error

```
SqlConnection is registered using the 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope. Please see https://simpleinjector.org/scoped for more information about how apply lifestyles and manage scopes.
```
I think this is expected since `options.AddAspNetCore()` wraps requests in SI scope.

**Comment by dotnetjunkie** [comment]
Are those first-chance exceptions? Does this happen in the debugger, does the program continue when you press F5 or does the program crash?

**Comment by stevencovhlth** [comment]
they are not first-chance exceptions.  The program spits out the DeveloperExceptionPage as a result of F5

**Comment by dotnetjunkie** [comment]
This means that now is the timenyou post the exception details. Full stack trace of the exception and that of all inner eexceptions.

**Comment by stevencovhlth** [comment]
LOL! of course @dotnetjunkie it is.

`System.TypeLoadException: Could not load type 'Vortext.Common.Domain.Model.Entity' from assembly 'Vortext.Common.Domain, Version=1.7.6.0, Culture=neutral, PublicKeyToken=null'`

Seriously, that is it!
![image](https://user-images.githubusercontent.com/62948126/85330341-3c719600-b4a2-11ea-86b9-89e5d3667184.png)

**Comment by dotnetjunkie** [comment]
Can you post the srack trace in textual form?

**Comment by stevencovhlth** [comment]
OH!  sorry Stephen, here you go

```
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at SimpleInjector.SimpleInjectorAspNetCoreBuilderMvcCoreExtensions.RegisterMvcControllers(Container container, ApplicationPartManager manager)
   at SimpleInjector.SimpleInjectorAspNetCoreBuilderMvcCoreExtensions.AddControllerActivation(SimpleInjectorAspNetCoreBuilder builder)
   at Vortext.RCM.Api.Startup.<>c.<IntegrateSimpleInjector>b__6_0(SimpleInjectorAddOptions options) in C:\dev\vortext-main-new\vortext-web\Vortext.RCM.Api\Startup.cs:line 68
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.AddSimpleInjector(IServiceCollection services, Container container, Action`1 setupAction)
   at Vortext.RCM.Api.Startup.IntegrateSimpleInjector(IServiceCollection services) in C:\dev\vortext-main-new\vortext-web\Vortext.RCM.Api\Startup.cs:line 65
   at Vortext.RCM.Api.Startup.ConfigureServices(IServiceCollection services) in C:\dev\vortext-main-new\vortext-web\Vortext.RCM.Api\Startup.cs:line 53
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Vortext.RCM.Api.Program.Main(String[] args) in C:\dev\vortext-main-new\vortext-web\Vortext.RCM.Api\Program.cs:line 23
```

**Comment by dotnetjunkie** [comment]
Looking at the call stack, this isn't so much a Simple Injector exception, but the problem would likely exist if you use the built-in container as well. All the ASP.NET Core integration for Simple Injector does is call MVC's `Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager` using the `Microsoft.AspNetCore.Mvc.Controllers.ControllerFeature` the same way MVC does for loading controllers. The error is thrown by .NET while loading a specific type from your assembly.

You seem to have your `Vortext.Common.Domain` project added as application part, and for some reason (a reason I cannot see) loading that particular type from that assembly fails.

My advice is the following: try building a minimal, reproducible example by starting with an empty ASP.NET Core MVC project, using the built-in container, using standard configuration, and slowly start adding things until the error pops up. When this happens, backtrack until you understand what is causing that type to fail.

One possible cause that comes to mind is that `Vortext.Common.Domain.Model.Entity` can't be loaded because it depends on a type from another assembly that can't be loaded. Perhaps due to a missing binding redirect?

**Comment by stevencovhlth** [comment]
Thank you @dotnetjunkie I will have a go at that.  I know it is going to be something simple and silly.  I don't register that library in core so I don't know why it would try to load that but I'll try your suggestion.

**Comment by stevencovhlth** [comment]
well drat that turned out to be a reference to another of my libraries that referenced an older version of my common library where `Entity` existed.  Once removed all worked well.  I'm still not sure why that project was called during registration of aspnetcore but it's fixed now.  Sorry for the hassle @dotnetjunkie .
