### ISSUE TITLE
Verification fails with IAsyncDisposable dependency in ServiceCollection

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector.Integration.AspNetCore#35]
In case a Simple Injector-registered component (the class `X` in the code below) directly or indirectly depends on a (through cross-wiring provided) ServiceCollection-registered component (the class `Y`) that implement `IAsyncDisposable` but not `IDisposable`, verification fails.

Code to reproduce:

``` c#
using Microsoft.Extensions.DependencyInjection;
using SimpleInjector;

var container = new Container();

new ServiceCollection()
	.AddSimpleInjector(container)
	.AddScoped<Y>()
	.BuildServiceProvider()
    .UseSimpleInjector(container);

container.Register<X>();

container.Verify();

public record X(Y Foo);
public record Y : IAsyncDisposable
{
	public ValueTask DisposeAsync() => default;
}
```

This results in the following exception:

> System.InvalidOperationException: ''Y' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.'

Stack trace:

```
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
at SimpleInjector.Scope.DisposeInstancesInReverseOrder(List`1 disposables, Int32 startingAsIndex)
at SimpleInjector.Scope.DisposeRecursively(Boolean operatingInException)
at SimpleInjector.Scope.Dispose(Boolean disposing)
at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
at SimpleInjector.Container.Verify(VerificationOption option)
at Program.<Main>$(String[] args)
```

**Comment by dotnetjunkie** [comment]
A possible fix for this issue is, unfortunately, unfeasible. While the Simple Injector core library skips disposal of classes that only implement `IAsyncDisposable` during verification, it's impossible to instruct the `ServiceScope` to do the same.

I will, therefore, be closing this issue. The workaround/solution is to wrap the call to `Verify()` in a scope. e.g.:

``` c#
await using (AsyncScopedLifestyle.BeginScope(container))
{
    container.Verify();
}
```

Another option is to remove the call to `Verify()` completely and rely on the container's auto-verification feature (`Container.Options.EnableAutoVerification`). It ensures that at the first resolve the container is verified. As this resolve would typically live inside a scope, it has the same effect as the previous code snippet, with the main difference that the application only fails when the first request is made, instead of during startup.
